export enum WINDOW_NAME {
    MAIN = "main",
    SETTINGS = "settings",
    ABOUT = "about",
}

export enum CONTEXTMENU_CODE {
    COPY = "CONTEXTMENU_CODE_COPY",
    DELETE = "CONTEXTMENU_CODE_DELETE",
    TOP = "CONTEXTMENU_CODE_TOP",
    RENAME = "CONTEXTMENU_CODE_RENAME",
    REFIRES = "CONTEXTMENU_CODE_REFRESH",
}

export enum TRAY_CONTEXTMENU_CODE {
    QUIT = "TRAY_CONTEXTMENU_CODE_QUIT",
    OPEN_MAIN_WINDOW = "TRAY_CONTEXTMENU_CODE_OPEN_MAIN_WINDOW",
}

export enum THEME_MODE {
    LIGHT = "light",
    DARK = "dark",
    SYSTEM = "system",
}
